# Site settings
title: Ohblog
header-img: img/home-bg.jpg
email: email.ohna2s@gmail.com
copyright_name: Ohna2s Blog
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "https://ohna2s.github.io"
author: ohna2s
twitter_username: ohna2s
github_username:  ohna2s
facebook_username:  ohna2s
email_username:  email.ohna2s@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
