# Site settings
title: Ohblog
header-img: img/home-bg.jpg
email: email.ohna2s@gmail.com
copyright_name: Ohlog
description: "Just another personal blog of Ohna2s"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ohna2s.github.io"
author: ohna2s
twitter_username: ohna2s
github_username:  ohna2s
facebook_username:  ohna2s

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
